In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.3.0'

## Hello World in TensorFLow

In [3]:
h = tf.constant("Hello")

In [4]:
w = tf.constant("World")

In [5]:
hw = h + w

In [6]:
hw

<tf.Tensor 'add:0' shape=() dtype=string>

In [7]:
with tf.Session() as sess:
    res = sess.run(hw)

In [8]:
res

b'HelloWorld'

### Graphs, Sessions & Fetches

In [9]:
a = tf.constant(5)
b = tf.constant(7)
c = tf.constant(10)

In [10]:
d = tf.multiply(a,b)
e = tf.add(b,c)
f = tf.subtract(d,e)

In [11]:
with tf.Session() as sess:
    out = sess.run(f)

In [12]:
out

18

In [13]:
tf.get_default_graph()

In [14]:
g = tf.Graph()

In [15]:
g

In [16]:
a = tf.constant(5)

In [20]:
a.graph is tf.get_default_graph()

True

In [21]:
with g.as_default():
    a = tf.constant(77)
    print (a.graph)

### Fetches 

In [26]:
a = tf.constant(5)
b = tf.constant(7)
c = tf.constant(10)
d = tf.multiply(a,b)
e = tf.add(b,c)
f = tf.subtract(d,e)
with tf.Session() as sess:
    out = sess.run(f)

In [27]:
with tf.Session() as sess:
    fetches = [a,b,c,d,e,f]
    outs = sess.run(fetches)

print(outs)

[5, 7, 10, 35, 17, 18]


### Data Types

In [28]:
c = tf.constant(4.0, dtype=tf.float64)

In [29]:
d = tf.cast(c,tf.float16)

In [30]:
d.dtype

tf.float16

### Tensor Arrays & Shapes

In [31]:
c = tf.constant( [[1,2,3],[4,5,6]])

In [32]:
import numpy as np

In [34]:
d = np.array([ [1,2,3], [4,5,6]])

In [35]:
tf.constant(d)

<tf.Tensor 'Const_14:0' shape=(2, 3) dtype=int32>

In [37]:
d = tf.linspace(start=2.0,stop=10.0, num=20)

In [39]:
with tf.Session() as sess:
    o = sess.run(d)

In [40]:
o

array([  2.        ,   2.42105269,   2.84210539,   3.26315784,
         3.68421054,   4.10526323,   4.52631569,   4.94736862,
         5.36842108,   5.78947353,   6.21052647,   6.63157892,
         7.05263138,   7.47368431,   7.89473677,   8.31579018,
         8.73684216,   9.15789413,   9.57894707,  10.        ], dtype=float32)

In [41]:
s = tf.fill((4,5),100)

In [44]:
with tf.Session() as sess:
    o = sess.run(s)
    print (o.shape)

(4, 5)


In [43]:
o

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [45]:
A = tf.constant( [
                   [1,2,3],
                   [4,5,6]
                 ])

In [47]:
b = tf.constant( [1,0,1])

In [48]:
b = tf.expand_dims(b,1)

In [49]:
b.shape

TensorShape([Dimension(3), Dimension(1)])

In [50]:
A.shape

TensorShape([Dimension(2), Dimension(3)])

In [51]:
matmul = tf.matmul(A,b)

In [54]:
with tf.Session() as sess:
    o = sess.run(matmul)
    print (sess.run(b))

[[1]
 [0]
 [1]]


In [53]:
o

array([[ 4],
       [10]])

In [55]:
with tf.Session() as sess:
    fetches = [A,b]
    outs = sess.run(fetches)

In [56]:
outs

[array([[1, 2, 3],
        [4, 5, 6]]), array([[1],
        [0],
        [1]])]

In [57]:
r = tf.transpose(A)

In [58]:
with tf.Session() as sess:
    fetches = [r]
    outs = sess.run(fetches)

In [59]:
outs

[array([[1, 4],
        [2, 5],
        [3, 6]])]

### Variables & Placeholders

In [60]:
init_vals = tf.random_normal((1,5),0,1)

In [61]:
init_vals.shape

TensorShape([Dimension(1), Dimension(5)])

In [62]:
var = tf.Variable(init_vals)

In [63]:
init = tf.global_variables_initializer()

In [65]:
with tf.Session() as sess:
    sess.run(init)
    print ( sess.run(var))

[[-0.3748953  -1.20144737 -1.09303975 -1.67744994  0.39071032]]


### Placeholders 

In [91]:
ph = tf.placeholder(tf.int16)

In [92]:
d = tf.multiply(ph,2)
    

In [93]:
with tf.Session() as sess:
    print(sess.run(d, feed_dict={ph:5}))
    print(sess.run(d, feed_dict={ph:15}))

10
30
